### ISSUE TITLE
the quantity is not checked "*"

### ISSUE THREAD

**Issue by LazarenkoA** [clintjedwards/avail#1]
if you make a pattern consisting of * less than 6 there will be a panic

**Comment by clintjedwards** [comment]
I wasn't able to reproduce this, could you give an example expression?

Example here: https://play.golang.org/p/uf5B6PTjZyp

**Comment by LazarenkoA** [comment]
https://play.golang.org/p/S28IcPvYvIY 

```
panic: runtime error: index out of range [5] with length 5

goroutine 1 [running]:
github.com/clintjedwards/avail.New(0x4f5fa1, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/gopath327410737/pkg/mod/github.com/clintjedwards/avail@v1.0.0/avail.go:71 +0x91d
main.main()
	/tmp/sandbox891657114/prog.go:11 +0x4b
```

**Comment by clintjedwards** [comment]
Ah good find. Regexes are hard and confusing and probably the most brittle part of this entire thing. Fix coming soon.
